// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBPncVgMEyT6LwaHGeks_wRBd1X0jG2dk',
    appId: '1:514387400371:web:9c9d66bd467452133cc2c6',
    messagingSenderId: '514387400371',
    projectId: 'food-deliver-c941c',
    authDomain: 'food-deliver-c941c.firebaseapp.com',
    storageBucket: 'food-deliver-c941c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfuZ1orEkdApDSXKXIEI2VT7dutL0O48k',
    appId: '1:514387400371:android:a5e4c3b916d32b3d3cc2c6',
    messagingSenderId: '514387400371',
    projectId: 'food-deliver-c941c',
    storageBucket: 'food-deliver-c941c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADKPaPRbDZ1qOch6bCuWUzBuQNeV8f-zY',
    appId: '1:514387400371:ios:e7899fd298ed90943cc2c6',
    messagingSenderId: '514387400371',
    projectId: 'food-deliver-c941c',
    storageBucket: 'food-deliver-c941c.appspot.com',
    iosClientId: '514387400371-htsbq5pode6cudaug1p1cvk4f0scs491.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADKPaPRbDZ1qOch6bCuWUzBuQNeV8f-zY',
    appId: '1:514387400371:ios:8cf418e45b3e3f1c3cc2c6',
    messagingSenderId: '514387400371',
    projectId: 'food-deliver-c941c',
    storageBucket: 'food-deliver-c941c.appspot.com',
    iosClientId: '514387400371-vfbi8m5m23firtf9mlit33rl6qgrtkas.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodapp.RunnerTests',
  );
}

